# Generated by Django 3.1.3 on 2021-08-23 07:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=18, max_digits=20)),
                ('long', models.DecimalField(decimal_places=18, max_digits=20)),
                ('bath_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bed_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
